---
- name: install ius
  sudo: true
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: install python
  sudo: true
  yum:
    name:
      - python36u
      - python36u-libs
      - python36u-devel
      - python36u-pip
    update_cache: true
