---
# This one makes a deps update
- name: Install common dependencies
  sudo: true
  yum:
    name:
      - ruby
      - vim
      - git
      - tmux
      - gcc
      - wget
    state: latest

- name: Download vimrc
  get_url:
    url: https://raw.githubusercontent.com/marek2901/config_files/master/.vimrc
    dest: ~/
